<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $person = array('Administrator', 'System', '', 'M', '1970-01-01', 'admin@admin.com', 'Administrator', '{}','09773620038');

        $p = new \App\Person();
        $p->LastName = $person[0];
        $p->FirstName = $person[1];
        $p->MiddleName = $person[2];
        $p->Gender = $person[3];
        $p->Birthday = $person[4];
        $p->Email = $person[5];
        $p->Position = $person[6];
        $p->ImageFile = $person[7];
        $p->ContactNumber = $person[8];
        $p->save();
        $p->created_by = 1;
        $p->updated_by = 1;
        $p->save();

        $user = array('admin','admin',1,1,24);

        $u = new App\User();
        $u->Username = 'admin';
        $u->Password = 'admin';
        $u->Person = 1;
        $u->Status = 1;
        $u->save();
        $u->created_by = 1;
        $u->updated_by = 1;
        $u->save();

        auth()->login($u);

        $costCenters = array(
            array('00', 'General / Other Expenses'),
            array('01', 'Se'),
            array('02', 'CD'),
            array('03', 'E2'),
            array('04', 'PM'),
            array('06', 'Te'),
            array('11', 'PE'),
            array('12', 'Lab'),
            array('13', 'WWT'),
            array('14', 'FAC'),
            array('21', 'QA'),
            array('22', 'GS'),
            array('23', 'Purch'),
            array('24', 'PP/Whse'),
            array('25', 'EHS/EQMS'),
            array('31', 'F&A - SS'),
            array('32', 'EO - SS'),
            array('33', 'HR - SS'),
            array('34', 'IT - SS'),
            array('35', 'Sales - SS'),
            array('41', 'F&A - Dir'),
            array('42', 'EO - Dir'),
            array('43', 'HR - Dir'),
            array('44', 'IT - Dir'),
            array('45', 'Sales - Dir'),
            array('46', 'EHS'),
            array('47', 'Material')
        );

        foreach($costCenters as $costCenter) {
            $cc = new CostCenter();
            $cc->Code = $costCenter[0];
            $cc->Description = $costCenter[1];
            $cc->save();
        }

        $permissions = array(
            array('Reports', 'V'),
            array('Invoices', 'V'),
            array('Invoices', 'M'),
            array('Deliveries', 'V'),
            array('Deliveries', 'M'),
            array('Bills', 'V'),
            array('Bills', 'M'),
            array('Payments', 'V'),
            array('Payments', 'M'),
            array('ReceiveOrders', 'V'),
            array('ReceiveOrders', 'M'),
            array('PurchaseReturns', 'V'),
            array('PurchaseReturns', 'M'),
            array('PurchaseOrders', 'V'),
            array('PurchaseOrders', 'M'),
            array('PurchaseOrders', 'A'),
            array('StockTransfers', 'V'),
            array('StockTransfers', 'M'),
            array('StockTransfers', 'A'),
            array('StockAdjustments', 'V'),
            array('StockAdjustments', 'M'),
            array('StockAdjustments', 'A'),
            array('Locations', 'V'),
            array('Locations', 'M'),
            array('UnitsOfMeasure', 'V'),
            array('UnitsOfMeasure', 'M'),
            array('Categories', 'V'),
            array('Categories', 'M'),
            array('Products', 'V'),
            array('Products', 'M'),
            array('InventoryLogs', 'V'),
            array('Departments', 'V'),
            array('Departments', 'M'),
            array('Issuances', 'V'),
            array('Issuances', 'M'),
            array('Issuances', 'A'),
            array('PurchaseRequests', 'V'),
            array('PurchaseRequests', 'M'),
            array('PurchaseRequests', 'A'),
            array('Roles', 'V'),
            array('Roles', 'M'),
            array('GeneralLedgers', 'V'),
            array('GeneralLedgers', 'M'),
            array('UserAccounts', 'V'),
            array('UserAccounts', 'M'),
            array('Suppliers', 'V'),
            array('Suppliers', 'M'),
            array('ProductLines', 'V'),
            array('ProductLines', 'M'),
            array('ItemTypes', 'V'),
            array('ItemTypes', 'M'),
            array('Quotes', 'V'),
            array('Quotes', 'M'),
            array('Currencies', 'V'),
            array('Currencies', 'M'),
            array('DataManagement', 'V'),
            array('DataManagement', 'M'),
            array('CostCenters', 'V'),
            array('CostCenters', 'M'),
        );

        foreach ($permissions as $permission) {
            $p = new \App\Permission();
            $p->Module = $permission[0];
            $p->Permission = $permission[1];
            $p->save();
        }

        $roles = array(
            array('Supervisor', '[44,45]'),
            array('Manager', '[40,44,45,46,1]'),
            array('Director', '[54]'),
            array('OperationsManager', '[38,39,6,7,29,30,27,28,36,37,4,5,40,41,33,44,45,46,1,21,22,19,20,25,26,23,24,54,55]'),
            array('GeneralManager', '[40,44,45,46,1]'),
            array('Administrator', '[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55]')
        );

        foreach ($roles as $role) {
            $r = new \App\Role();
            $r->Name = $role[0];
            $r->Permissions = $role[1];
            $r->save();
        }

        $persons = array(
            array('Castelo', 'Erwin', '', 'M', '1970-01-01', 'Erwin.Castelo@ii-vi.com', 'Plant Manager', '{}',''),
            array('Dahl', 'Leigh James', '', 'M', '1970-01-01', 'Leigh.Dahl@ii-vi.com', 'General Manager', '{}',''),
            array('Agrasada', 'Frozti Ann', '', 'F', '1970-01-01', 'Frozti.Agrasada@ii-vi.com', 'HR Manager', '{}',''),
            array('Cinco', 'Eugenio', '', 'M', '1970-01-01', 'Eugenio.Cinco@ii-vi.com', 'Location Manager', '{}',''),
            array('Dumanat', 'Dennis', '', 'M', '1970-01-01', 'Dennis.Dumanat@ii-vi.com', 'Operations Director', '{}',''),
            array('Saria', 'Juan Miguel', '', 'M', '1970-01-01', 'JuanMiguel.Saria@ii-vi.com', 'Network and Systems Administrator', '{}',''),
            array('Danao', 'Vicente', '', 'M', '1970-01-01', 'Vicente.Danao@ii-vi.com', 'Purchasing Manager', '{}',''),
            array('Rosario', 'Jermin', '', 'M', '1970-01-01', 'Jermin.Rosario@ii-vi.com', 'Optics Production Manager', '{}',''),
            array('Castillo', 'Emerson', '', 'M', '1970-01-01', 'Emerson.Castillo@ii-vi.com', 'Instrumentation Manager', '{}','')
        );

        foreach ($persons as $person) {
            $p = new \App\Person();
            $p->LastName = $person[0];
            $p->FirstName = $person[1];
            $p->MiddleName = $person[2];
            $p->Gender = $person[3];
            $p->Birthday = $person[4];
            $p->Email = $person[5];
            $p->Position = $person[6];
            $p->ImageFile = $person[7];
            $p->ContactNumber = $person[8];
            $p->save();
        }

        $users = array(
            array('ecastelo', '1234', 2, 1, 23),
            array('jmsaria', '1234', 7, 1, 18),
            array('ddumanat', '1234', 6, 1, 21),
            array('fagrasada', '1234', 4, 1, 17),
            array('ldahl', '1234', 3, 1, 24)
        );

        foreach ($users as $user) {
            $u = new App\User();
            $u->Username = $user[0];
            $u->Password = $user[1];
            $u->Person = $user[2];
            $u->Status = $user[3];
            $u->save();
        }

        // add after.
        array_push($users, $user);

        $glcodes = array(
            array('13100-00-06', 'FINISHED GOODS INVTY - CRTE'),
            array('13200-00-06', 'WORK IN PROCESS INVTY - CRTE'),
            array('13300-00-11', 'RAW MATERIALS INVTY -Sc'),
            array('13310-00-06', 'RAW MAT. IN TRANSIT - CRTE'),
            array('13400-00-06', 'RESIDUE INVENTORY - CRTE'),
            array('13500-00-02', 'PROCESS CHEMICAL INVTY - OB'),
            array('13500-00-03', 'PROCESS CHEMICAL INVTY - CRSC'),
            array('13500-00-09', 'PROCESS CHEMICAL INVTY'),
            array('13500-00-11', 'PROCESS CHEMICAL INVTY -Sc'),
            array('13500-01-00', 'PROCESS CHEMICAL INVTY - CRSE'),
            array('13610-00-02', 'FACTORY SUPPLIES INVTY - OB'),
            array('13610-00-03', 'FACTORY SUPPLIES INVTY - CRSC'),
            array('13610-00-09', 'FACTORY SUPPLIES INVTY'),
            array('13610-00-11', 'FACTORY SUPPLIES INVTY -Sc'),
            array('13610-01-00', 'FACTORY SUPPLIES INVTY - CRSE'),
            array('13620-00-03', 'LABORATORY SUPPLIES INVTY - CRSC'),
            array('13620-00-09', 'LABORATORY SUPPLIES INVTY'),
            array('13620-00-11', 'LABORATORY SUPPLIES INVTY -Sc'),
            array('13620-01-00', 'LABORATORY SUPPLIES INVTY - CRSE'),
            array('15190-00-01', 'CAPEX IN PROGRESS - CRSE'),
            array('15190-00-02', 'CAPEX IN PROGRESS - OB'),
            array('15190-00-03', 'CAPEX IN PROGRESS - CRSC'),
            array('15190-00-05', 'CAPEX IN PROGRESS - SE'),
            array('15190-00-06', 'CAPEX IN PROGRESS-CRTE'),
            array('15190-00-09', 'CAPEX IN PROGRESS'),
            array('15190-00-11', 'CAPEX IN PROGRESS -Sc'),
            array('51000-03-03', 'MC-DIRECT MATERIALS - CRSC'),
            array('51000-03-11', 'MC-DIRECT MATERIALS -Sc'),
            array('51000-04-04', 'MC-DIRECT MATERIALS - PM/OTH'),
            array('52100-01-00', 'MC-PROCESS CHEMICALS - CRSE'),
            array('52100-01-05', 'MC-PROCESS CHEM - SE PRM'),
            array('52100-02-02', 'MC-PROCESS CHEM - OB'),
            array('52100-03-03', 'MC-PROCESS CHEM - CRSC'),
            array('52100-03-11', 'MC-PROCESS CHEM -Sc'),
            array('52100-04-04', 'MC-PROCESS CHEM - PM/OTH'),
            array('52100-06-06', 'MC-PROCESS CHEM - CRTE'),
            array('52100-06-08', 'MC-PROCESS CHEM -Te UHP'),
            array('53001-01-00', 'MC-FACTORY SUPPLIES- CRSE'),
            array('53001-01-05', 'MC-FACTORY SUPPLIES-SE'),
            array('53001-02-02', 'MC-FACTORY SUPPLIES-OB'),
            array('53001-03-03', 'MC-FACTORY SUPPLIES-CRSC'),
            array('53001-03-11', 'MC-FACTORY SUPPLIES-Sc'),
            array('53001-04-04', 'MC-FACTORY SUPPLIES-PM/OTH'),
            array('53001-06-06', 'MC-FACTORY SUPPLIES-CRTE'),
            array('53001-06-08', 'MC-FACTORY SUPPLIES-Te UHP'),
            array('53001-11-00', 'MC-FACTORY SUPPLIES-TG'),
            array('53001-12-00', 'MC-FACTORY SUPPLIES-LAB'),
            array('53001-13-00', 'MC-FACTORY SUPPLIES-WM'),
            array('53001-14-00', 'MC-FACTORY SUPPLIES-FAC'),
            array('53001-36-00', 'MC-FCTRY SUPP-QMS'),
            array('53001-37-00', 'MC-FACTORY SUPPLIES-MAT'),
            array('53001-46-00', 'MC-FCTRY SUPP-QMS'),
            array('53002-01-00', 'MC-LAB SUPPLIES-CRSE'),
            array('53002-01-05', 'MC-LAB SUPPLIES-SE'),
            array('53002-03-03', 'MC-LAB SUPPLIES-CRSC'),
            array('53002-03-11', 'MC-LAB SUPPLIES-Sc'),
            array('53002-04-04', 'MC-LAB SUPPLIES-PM/OTH'),
            array('53002-06-06', 'MC-LAB SUPPLIES-CRTE'),
            array('53002-06-08', 'MC-LAB SUPPLIES-Te UHP'),
            array('53002-11-00', 'MC-LAB SUPPLIES-TG'),
            array('53002-12-00', 'MC-LAB SUPPLIES-LAB'),
            array('53002-13-00', 'MC-LAB SUPPLIES-WM'),
            array('53002-14-00', 'MC-LAB SUPPLIES-FAC'),
            array('53002-36-00', 'MC-LAB SUPPLIES-QMS'),
            array('53002-37-00', 'MC-LAB SUPPLIES-MAT'),
            array('53002-46-00', 'MC-LAB SUPPLIES-QMS'),
            array('53003-01-00', 'MC-FUEL & OIL-CRSE'),
            array('53003-01-05', 'MC-FUEL & OIL-SE'),
            array('53003-02-02', 'MC-FUEL & OIL-OB'),
            array('53003-03-03', 'MC-FUEL & OIL-CRSC'),
            array('53003-03-11', 'MC-FUEL & OIL-Sc'),
            array('53003-04-04', 'MC-FUEL & OIL-PM/OTH'),
            array('53003-06-06', 'MC-FUEL & OIL-CRTE'),
            array('53003-06-08', 'MC-FUEL & OIL-Te UHP'),
            array('53003-13-00', 'MC-FUEL & OIL-WM'),
            array('53003-14-00', 'MC-FUEL & OIL-FAC'),
            array('53003-36-00', 'MC-FUEL & OIL-QMS'),
            array('53003-37-00', 'MC-FUEL & OIL-MAT'),
            array('53003-46-00', 'MC-FUEL & OIL-QMS'),
            array('53005-01-00', 'MC-REPAIRS & MAINT-CRSE'),
            array('53005-01-05', 'MC-REPAIRS & MAINT-SE'),
            array('53005-02-02', 'MC-REPAIRS & MAINT-OB'),
            array('53005-03-03', 'MC-REPAIRS & MAINT-CRSC'),
            array('53005-03-11', 'MC-REPAIRS & MAINT-Sc'),
            array('53005-04-04', 'MC-REPAIRS & MAINT-PM/OTH'),
            array('53005-06-06', 'MC-REPAIRS & MAINT-CRTE'),
            array('53005-06-08', 'MC-REPAIRS & MAINT-Te UHP'),
            array('53005-11-00', 'MC-REPAIRS & MAINT-TG'),
            array('53005-12-00', 'MC-REPAIRS & MAINT-LAB'),
            array('53005-13-00', 'MC-REPAIRS & MAINT-WM'),
            array('53005-14-00', 'MC-REPAIRS & MAINT-FAC'),
            array('53005-36-00', 'MC-REPAIRS & MAINT-QMS'),
            array('53005-37-00', 'MC- REPAIRS & MAINT-MAT'),
            array('53005-46-00', 'MC-REPAIRS & MAINT-QMS'),
            array('53006-06-06', 'MC-HANDLING & DOC-CRTE'),
            array('53007-01-00', 'MC-ENVI & SAFETY-CRSE'),
            array('53007-01-05', 'MC-ENVI & SAFETY-SE'),
            array('53007-02-02', 'MC-ENVI & SAFETY-OB'),
            array('53007-03-03', 'MC-ENVI & SAFETY-CRSC'),
            array('53007-04-04', 'MC-ENVI & SAFETY-PM/OTH'),
            array('53007-06-08', 'MC-ENVI & SAFETY-Te UHP'),
            array('53007-36-00', 'MC-ENVI & SAFETY-QMS'),
            array('53007-46-00', 'MC-ENVI & SAFETY-QMS'),
            array('53009-01-00', 'MC-MISCELLANEOUS-CRSE'),
            array('53009-01-05', 'MC-MISCELLANEOUS-SE'),
            array('53009-02-02', 'MC-MISCELLANEOUS-OB'),
            array('53009-03-03', 'MC-MISCELLANEOUS-CRSC'),
            array('53009-04-04', 'MC-MISCELLANEOUS-PM/OTH'),
            array('53009-06-06', 'MC-MISCELLANEOUS-CRTE'),
            array('53009-11-00', 'MC-MISCELLANEOUS-TG'),
            array('53009-12-00', 'MC-MISCELLANEOUS-LAB'),
            array('53009-13-00', 'MC-MISCELLANEOUS-WM'),
            array('53009-14-00', 'MC-MISCELLANEOUS-FAC'),
            array('53009-36-00', 'MC-MISCELLANEOUS-QMS'),
            array('53009-37-00', 'MC-MISCELLANEOUS-MAT'),
            array('53009-46-00', 'MC-MISCELLANEOUS-QMS'),
            array('53016-13-00', 'MC-TAXES & LICENSES-WM'),
            array('53019-01-00', 'MC-WW TREATMENT-CRSE'),
            array('53019-01-05', 'MC-WW TREATMENT-SE'),
            array('53019-02-02', 'MC-WW TREATMENT-OB'),
            array('53019-03-03', 'MC-WW TREATMENT-CRSC'),
            array('53019-03-11', 'MC-WW TREATMENT-Sc'),
            array('53019-04-04', 'MC-WW TREATMENT-PM/OTH'),
            array('53019-06-06', 'MC-WW TREATMENT-TE'),
            array('53019-06-08', 'MC-WW TREATMENT-Te UHP'),
            array('53019-13-00', 'MC-WW TREATMENT-WM'),
            array('53026-01-00', 'MC-EMP BEN- UNIFORM-CRSE'),
            array('53026-01-05', 'MC-EMP BEN-UNIFORM-SE'),
            array('53026-02-02', 'MC-EMP BEN- UNIFORM-OB'),
            array('53026-03-03', 'MC-EMP BEN- UNIFORM-CRSC'),
            array('53026-04-04', 'MC-EMP BEN- UNIFORM-PM/OTH'),
            array('53026-11-00', 'MC-EMP BEN- UNIFORM-TG'),
            array('53026-12-00', 'MC-EMP BEN- UNIFORM-LAB'),
            array('53026-13-00', 'MC-EMP BEN- UNIFORM-WM '),
            array('53026-14-00', 'MC-EMP BEN- UNIFORM-FAC'),
            array('53026-36-00', 'MC-EMP BEN- UNIFORM-QMS'),
            array('53026-37-00', 'MC-EMP BEN- UNIFORM-MAT'),
            array('53026-46-00', 'MC-EMP BEN- UNIFORM-QMS'),
            array('53040-01-00', 'MC-PACKAGING SUPPLIES-CRSE'),
            array('53040-01-05', 'MC-PACKAGING SUPPLIES-SE'),
            array('53040-02-02', 'MC-PACKAGING SUPPLIES-OB'),
            array('53040-03-03', 'MC-PACKAGING SUPPLIES-CRSC'),
            array('53040-03-11', 'MC-PACKAGING SUPPLIES-Sc'),
            array('53040-04-04', 'MC-PACKAGING SUPPLIES-PM/OTH'),
            array('53040-06-06', 'MC - PACKAGING SUPPLIES-CRTE'),
            array('53040-06-08', 'MC-PACKAGING SUPPL-Te UHP'),
            array('53040-12-00', 'MC-PACKAGING SUPPLIES-LAB'),
            array('53040-12-01', 'MC-PACKAGING SUPPLIES-LAB-SE'),
            array('53040-12-02', 'MC-PACKAGING SUPPLIES-LAB-OB'),
            array('53040-12-03', 'MC-PACKAGING SUPPLIES-LAB-E2'),
            array('53040-12-04', 'MC-PACKAGING SUPPLIES-LAB-PM'),
            array('53040-12-05', 'MC-PACKAGING SUPPLIES-LAB-SE'),
            array('53040-12-06', 'MC-PACKAGING SUPPLIES-LAB-TE'),
            array('53047-01-00', 'MC-SEM & TRAINING-CRSE'),
            array('53047-01-05', 'MC-SEM & TRAINING-SE'),
            array('53047-02-02', 'MC-SEM & TRAINING-OB'),
            array('53047-03-03', 'MC-SEM & TRAINING-CRSC'),
            array('53047-03-11', 'MC-SEM & TRAINING-Sc'),
            array('53047-04-04', 'MC-SEM & TRAINING-PM/OTH'),
            array('53047-11-00', 'MC-SEM & TRAINING-TG'),
            array('53047-12-00', 'MC-SEM & TRAINING-LAB'),
            array('53047-13-00', 'MC-SEM & TRAINING-WM'),
            array('53047-14-00', 'MC-SEM & TRAINING-FAC'),
            array('53047-36-00', 'MC-SEM & TRAINING-QMS'),
            array('53047-37-00', 'MC-SEM & TRAINING-MAT'),
            array('53047-46-00', 'MC-SEM & TRAINING-QMS'),
            array('53047-47-00', 'MC-SEM & TRAINING-MAT'),
            array('53048-06-06', 'MC - OUTSIDE LAB SVCS-CRTE'),
            array('57128-35-00', 'SL - REPAIRS & MAINT'),
            array('57128-45-00', 'SL - REPAIRS & MAINT'),
            array('57131-35-00', 'SL - OFFICE SUPPLIES'),
            array('57131-45-00', 'SL - OFFICE SUPPLIES'),
            array('57134-35-00', 'SL - MISCELLANEOUS'),
            array('57134-45-00', 'SL - MISCELLANEOUS'),
            array('58009-33-00', 'GA - EMP BEN-UNIFORM HR'),
            array('58009-43-00', 'GA - OFFICE SUPPLIES HR '),
            array('58009-43-00', 'GA - COMMUNICATIONS HR '),
            array('58009-43-00', 'GA - MISCELLANEOUS HR '),
            array('58009-43-00', 'GA - EMP BEN-UNIFORM HR'),
            array('58009-43-00', 'GA - EMP BEN - RICE HR '),
            array('58009-43-00', 'GA - REP & ENT HR '),
            array('58009-43-00', 'GA - EMP BEN – HOUSING-HR'),
            array('58009-43-00', 'GA - SEM. & TRAINING HR '),
            array('58009-43-00', 'GA - EMP BEN - MED HR '),
            array('58009-43-00', 'GA - REPAIRS & MAINT HR '),
            array('58009-47-00', 'GA-EMP BEN-UNIFORM MTRLS'),
            array('58010-33-00', 'GA - EMP BEN - RICE HR '),
            array('58014-33-00', 'GA - EMP BEN – HOUSING-HR'),
            array('58015-33-00', 'GA - EMP BEN - MED HR '),
            array('58024-33-00', 'GA - REP & ENT HR '),
            array('58025-31-00', 'GA - REPAIRS & MAINT ADM'),
            array('58025-33-00', 'GA - REPAIRS & MAINT HR '),
            array('58025-34-00', 'GA - REPAIRS & MAINT IT'),
            array('58025-37-00', 'GA - REPAIRS & MAINT MTRLS'),
            array('58025-41-00', 'GA - REPAIRS & MAINT ADM'),
            array('58025-44-00', 'GA - REPAIRS & MAINT IT'),
            array('58025-46-00', 'GA - REPAIRS & MAINT EHS'),
            array('58025-47-00', 'GA - REPAIRS & MAINT MTRLS'),
            array('58026-31-00', 'GA - COMMUNICATIONS ADM'),
            array('58026-33-00', 'GA - COMMUNICATIONS HR '),
            array('58026-34-00', 'GA - COMMUNICATIONS IT'),
            array('58026-41-00', 'GA - COMMUNICATIONS ADM'),
            array('58026-44-00', 'GA - COMMUNICATIONS IT'),
            array('58031-31-00', 'GA - OFFICE SUPPLIES ADM'),
            array('58031-33-00', 'GA - OFFICE SUPPLIES HR '),
            array('58031-34-00', 'GA - OFFICE SUPPLIES IT'),
            array('58031-37-00', 'GA - OFFICE SUPPLIES MTRLS'),
            array('58031-41-00', 'GA - OFFICE SUPPLIES ADM'),
            array('58031-44-00', 'GA - OFFICE SUPPLIES IT'),
            array('58031-46-00', 'GA - OFFICE SUPPLIES EHS'),
            array('58031-47-00', 'GA - OFFICE SUPPLIES MTRLS'),
            array('58037-31-00', 'GA - MISCELLANEOUS ADM'),
            array('58037-33-00', 'GA - MISCELLANEOUS HR '),
            array('58037-34-00', 'GA - MISCELLANEOUS IT'),
            array('58037-41-00', 'GA - MISCELLANEOUS ADM'),
            array('58037-44-00', 'GA - MISCELLANEOUS IT'),
            array('58039-31-00', 'GA - SEM. & TRAINING ADM'),
            array('58039-33-00', 'GA - SEM. & TRAINING HR '),
            array('58039-34-00', 'GA - SEM. & TRAINING IT'),
            array('58039-41-00', 'GA - SEM. & TRAINING ADM'),
            array('58039-44-00', 'GA - SEM. & TRAINING IT')
        );

        foreach($glcodes as $glcode) {
            $g = new \App\GeneralLedger();
            $g->Code = $glcode[0];
            $g->Description = $glcode[1];
            $g->Status = 1;
            $g->save();
        }

        $departments = array(
            array('CR Selenium',4,23,1,1,0),
            array('Optical Blanking',2,24,2,1,0),
            array('Blanchard Project',2,24,2,1,0),
            array('CR Scandium',4,23,3,1,0),
            array('CR Tellurium',4,23,6,1,0),
            array('Technical Group',2,24,11,1,0),
            array('Laboratory Group',2,24,12,1,0),
            array('Waste Management Group',4,23,13,1,0),
            array('Facilities',4,23,14,1,0),
            array('Admin (Shared Services)',2,25,31,1,0),
            array('Human Resources (Shared Services)',5,24,33,1,0),
            array('Information Technology (Shared Services)',2,24,34,1,0),
            array('Sales and Logistics (Shared Services)',6,25,35,1,0),
            array('QMS Group (Shared Services)',2,24,36,1,0),
            array('Materials Group (Shared Services)',2,24,37,1,0),
            array('Admin',2,25,41,1,0),
            array('Human Resources',5,24,43,1,0),
            array('Information Technology',2,24,44,1,0),
            array('Sales and Logistics',6,25,45,1,0),
            array('QMS Group',2,24,46,1,0),
            array('Materials Group',2,24,47,1,0),
            array('Operations',4,24,NULL,1,1),
            array('Plant',2,25,NULL,1,1),
            array('Leadership',6,0,NULL,1,1),
        );

        foreach ($departments as $department) {
            $d = new \App\Department();
            $d->Name = $department[0];
            $d->Approver = $department[1];
            $d->Parent = $department[2];
            $d->GL = $department[3];
            $d->Status = $department[4];
            $d->Legacy = $department[5];
            $d->save();
        }

        $categories = array(
            array('FS', 'Factory Supplies'),
            array('LS', 'Laboratory Supplies'),
            array('PC', 'Process Chemical'),
            array('FG', 'Finished Gooods'),
            array('RM', 'Raw Materials'),
        );

        foreach ($categories as $category) {
            $c = new \App\Category();
            $c->Identifier = $category[0];
            $c->Description = $category[1];
            $c->Status = 1;
            $c->save();
        }

        $productLines = array(
            array('CM', 'Common'),
            array('OB', 'Optical Blanking'),
            array('E2', 'Scandium'),
            array('SE', 'Selenium'),
            array('TE', 'Tellurium'),
        );

        foreach ($productLines as $productLine) {
            $p = new \App\ProductLine();
            $p->Identifier = $productLine[0];
            $p->Description = $productLine[1];
            $p->Status = true;
            $p->save();
        }

        $uoms = array(
            array('Bag', 'BAG/S'),
            array('Bar', 'BAR/S'),
            array('Bundle', 'BDL/S'),
            array('Box', 'BOX/ES'),
            array('Bottle', 'BTL/S'),
            array('Can', 'CAN/S'),
            array('Cylinder', 'CYL/S'),
            array('Drum', 'DRUM/S'),
            array('Gallon', 'GAL/S'),
            array('Kilogram', 'KG/S'),
            array('Kiloliter', 'KL/S'),
            array('Pound', 'LB/S'),
            array('Liter', 'LITER/S'),
            array('Cubic Meter at NTP', 'M3@NTP'),
            array('Meter', 'METER/S'),
            array('Pack', 'PACK/S'),
            array('Pail', 'PAIL/S'),
            array('Pair', 'PAIR/S'),
            array('Piece', 'PC/S'),
            array('Ream', 'REAM/S'),
            array('Roll', 'ROLL/S'),
            array('Set', 'SET/S'),
            array('Unit', 'UNIT/S'),
            array('Pad', 'PAD/S'),
            array('Feet', 'FT'),
            array('Lot', 'LOT/S'),
            array('Gram', 'GRAM/S'),
            array('Cubic Meter', 'CU3M/S'),
            array('Sack', 'SACK/S'),
            array('Sheet', 'SHEET/S'),
            array('Length', 'LENGTH/S'),
            array('Tube', 'TUBE/S')
        );

        foreach ($uoms as $uom) {
            $u = new \App\UnitOfMeasure();
            $u->Name = $uom[0];
            $u->Abbreviation = $uom[1];
            $u->Status = 1;
            $u->save();
        }

        foreach ($departments as $department) {
            $d = \App\Department::where('Name','=',$department[0])->first();
            $d->Approver = $department[1];
            $d->Parent = $department[2];
            $d->GL = $department[3];
            $d->Status = $department[4];
            $d->save();
        }

        foreach($users as $user){
            $u = \App\User::where('Username','=',$user[0])->first();
            $u->Department = $user[4];
            $u->save();
        }

        $user = \App\User::find(1)->first();
        $user->Roles = '[6]'; // administrator
        $user->save();

        $itemType = new \App\ItemType();
        $itemType->Identifier = 'NM';
        $itemType->Description = 'Non Moving';
        $itemType->save();



        $locations = array(
            array('Default Location', 1),
            array('LAB-C8.2', 1),
            array('L2B2.6', 1),
            array('L2B3.29', 1),
            array('L2B5.10', 1),
            array('L2B6.16', 1),
            array('ELE-G3.1', 1),
            array('LAB-A5', 1),
            array('G2', 1),
            array('CD-Area', 1),
            array('L2B2.2', 1),
            array('L2B2.15', 1),
            array('ELE-H2.5', 1),
            array('L2B3.10', 1),
            array('SR-I5.2', 1),
            array('LAB-B3.3', 1),
            array('LAB-D7.3', 1),
            array('Q5A', 1),
            array('LAB-A3', 1),
            array('LAB-A4.2', 1),
            array('LAB-B2.1', 1),
            array('LAB-E7.3', 1),
            array('SR 4', 1),
            array('SRB2.4', 1),
            array('L2B6.37', 1),
            array('ELE-G3.2', 1),
            array('CIVIL ACCT', 1),
            array('SR B7', 1),
            array('G4', 1),
            array('ELE-I3.5', 1),
            array('ELE-G3.7', 1),
            array('SR-A6.1', 1),
            array('B3', 1),
            array('L2B2.16', 1),
            array('MINI SHLV1', 1),
            array('SR B4', 1),
            array('LAB-E4', 1),
            array('RMB5', 1),
            array('LAB-D8.4', 1),
            array('L2B1.19', 1),
            array('Q7A', 1),
            array('ELE-A4.2', 1),
            array('L6B', 1),
            array('ANNEX M', 1),
            array('L2B6.15', 1),
            array('ELE-D4.6', 1),
            array('G3/G4', 1),
            array('ELE-H2.3', 1),
            array('SR C5', 1),
            array('LAB-B5.2', 1),
            array('B8', 1),
            array('A3', 1),
            array('L3B', 1),
            array('L2B5.23', 1),
            array('SR-C2', 1),
            array('SR-H1.2', 1),
            array('LAB', 1),
            array('LAB-E6.5', 1),
            array('K', 1),
            array('ELE-C4.2', 1),
            array('D3', 1),
            array('D3A', 1),
            array('L2B1.30', 1),
            array('A7', 1),
            array('L5', 1),
            array('LAB-E7.2', 1),
            array('B6', 1),
            array('LAB-A6.2', 1),
            array('J3', 1),
            array('L2B', 1),
            array('L2B1.10', 1),
            array('L2B4.23', 1),
            array('ELE-J1.5', 1),
            array('L1A', 1),
            array('SR-G5.4', 1),
            array('ELE-F4.1', 1),
            array('LAB-D6.1', 1),
            array('LAB-B2', 1),
            array('ELE-K1.3', 1),
            array('MINI SHLV5', 1),
            array('R6', 1),
            array('P7', 1),
            array('SR B8', 1),
            array('ELE-C3.5', 1),
            array('H3', 1),
            array('L2B4.9', 1),
            array('LAB-C8', 1),
            array('LAB-C2.1', 1),
            array('J', 1),
            array('MINI SHLV4', 1),
            array('L2B6.14', 1),
            array('H7', 1),
            array('LAB-E3.3', 1),
            array('ELE-C4.3', 1),
            array('L2B5.9', 1),
            array('L2B6.23', 1),
            array('SR-C2.3', 1),
            array('H8', 1),
            array('ELE-J2.2', 1),
            array('WR-A1', 1),
            array('F2', 1),
            array('T', 1),
            array('Ele-I2 Are', 1),
            array('SR-C', 1),
            array('SR-I6', 1),
            array('M4N', 1),
            array('G7', 1),
            array('SR-A5.3', 1),
            array('WIRE AREA', 1),
            array('LAB-E3.1', 1),
            array('LAB-E5.2', 1),
            array('H6', 1),
            array('C5', 1),
            array('L2B6.31', 1),
            array('ELE-A2.8', 1),
            array('LAB-C3.1', 1),
            array('ELE-H2.1', 1),
            array('ELE-I2.4', 1),
            array('ELE-E2', 1),
            array('ELE-C2.2', 1),
            array('P2', 1),
            array('P-2', 1),
            array('S1', 1),
            array('P4', 1),
            array('ELE-J1.7', 1),
            array('F4B', 1),
            array('ELE-G1.6', 1),
            array('ANNEX P3', 1),
            array('ELE-B1.1', 1),
            array('LAB-C6.2', 1),
            array('LAB-A5.3', 1),
            array('H2', 1),
            array('L2B3.19', 1),
            array('L2B5.3-4', 1),
            array('LAB-D8.1', 1),
            array('LAB-D3.5', 1),
            array('ELE-H1.1', 1),
            array('L2B1.20', 1),
            array('O3', 1),
            array('ELE-J1.6', 1),
            array('Ele-K2.2', 1),
            array('ELE-H3.2', 1),
            array('E8', 1),
            array('ELE-G1.8', 1),
            array('ELE-B1.3', 1),
            array('SR-C2.2', 1),
            array('CIROSB1', 1),
            array('LAB-B1.3', 1),
            array('M1', 1),
            array('L2B1.32', 1),
            array('L2B6.2', 1),
            array('SR 2', 1),
            array('ELE-G1.7', 1),
            array('L2B4.5', 1),
            array('N', 1),
            array('E6', 1),
            array('L2B6.33', 1),
            array('SR-I3.3', 1),
            array('ELE-G4.7', 1),
            array('T1', 1),
            array('ELE-B3.2', 1),
            array('ELE-F2.1', 1),
            array('L2B2.3', 1),
            array('L8B4.19', 1),
            array('SR-B3.3', 1),
            array('ELE-B3.7', 1),
            array('FR-11', 1),
            array('LAB-B1.1', 1),
            array('LAB-D6.3', 1),
            array('Ele-L4.2', 1),
            array('F6A', 1),
            array('ELE-H3.1', 1),
            array('SR-H2.3', 1),
            array('LAB-B5.1', 1),
            array('SR-A8', 1),
            array('D4B', 1),
            array('ELE-D2.1', 1),
            array('L8B', 1),
            array('SR-A7.1', 1),
            array('LAB-D Area', 1),
            array('WR-A2', 1),
            array('QAS ACCT', 1),
            array('CH/WHSE', 1),
            array('LAB-B5', 1),
            array('LAB-C1.5', 1),
            array('B-GROUND', 1),
            array('F3', 1),
            array('SRF1.1', 1),
            array('LAB-A3.2', 1),
            array('O2', 1),
            array('L2B2.20', 1),
            array('LAB-E6.2', 1),
            array('ELE-G1.1', 1),
            array('R1', 1),
            array('ELE-K1.1', 1),
            array('SR-I3.4', 1),
            array('FR-15', 1),
            array('F7', 1),
            array('ELE-B3.3', 1),
            array('F6', 1),
            array('LAB-B3', 1),
            array('WHSE CABIN', 1),
            array('SR-B2.5', 1),
            array('LAB-E5.1', 1),
            array('SR-B3.4', 1),
            array('H', 1),
            array('ELE-B2.2', 1),
            array('ELE-B4.7', 1),
            array('ELE-I1.2', 1),
            array('LAB-E4.1', 1),
            array('SR-E2.2', 1),
            array('LAB-D3.4', 1),
            array('D8', 1),
            array('ELE-D3.5', 1),
            array('ELE-H4.6', 1),
            array('Q4', 1),
            array('L2B6.1', 1),
            array('SR-D3.1', 1),
            array('L2B5.12', 1),
            array('L2B6.27', 1),
            array('L2B4.1', 1),
            array('D6', 1),
            array('E', 1),
            array('OLD CNTEEN', 1),
            array('L2B6.21', 1),
            array('SRH3.2', 1),
            array('LAB-B4.2', 1),
            array('ELE-H1.5', 1),
            array('L2B6.7', 1),
            array('SR-A', 1),
            array('A2', 1),
            array('ELE-E4.1', 1),
            array('L2B1.7', 1),
            array('L2B1.29', 1),
            array('RMB9', 1),
            array('LAB-C4.1', 1),
            array('A', 1),
            array('FR-18', 1),
            array('SR-C7', 1),
            array('J2', 1),
            array('L2B3.5', 1),
            array('L2B5.27', 1),
            array('TANK', 1),
            array('L2B6.28', 1),
            array('ELE-B1.5', 1),
            array('J4', 1),
            array('L2B2.12', 1),
            array('L2B5.21', 1),
            array('ELE-A1.4', 1),
            array('LAB-C4', 1),
            array('A4', 1),
            array('ELE-G2.8', 1),
            array('ELE-D2.5', 1),
            array('L2B5.3', 1),
            array('SRB6.1', 1),
            array('L2B6.8', 1),
            array('LAB-C7.1', 1),
            array('Ele-K1.4', 1),
            array('E1', 1),
            array('ELE-I1.7', 1),
            array('L2B6.6', 1),
            array('SAFETY ACT', 1),
            array('L2B1.4', 1),
            array('ELE-H4.7', 1),
            array('G5', 1),
            array('L2B3.3', 1),
            array('SR-H2.5', 1),
            array('ELE-C3.2', 1),
            array('L2B5.28', 1),
            array('L2B6.25', 1),
            array('WHSE off', 1),
            array('ELE-B4.6', 1),
            array('H4', 1),
            array('L7B', 1),
            array('SR A-2', 1),
            array('ANNEX P2', 1),
            array('LAB-C7.5', 1),
            array('ELE-A4.6', 1),
            array('LAB-A1', 1),
            array('ELE-H2.2', 1),
            array('LAB-B4.1', 1),
            array('LAB-A6.3', 1),
            array('LAB-E8.4', 1),
            array('LAB-C5.3', 1),
            array('LAB-A9', 1),
            array('F2B', 1),
            array('L2B6.26', 1),
            array('SR-H3.3', 1),
            array('ELE-C3.3', 1),
            array('LAB-C6.4', 1),
            array('L1', 1),
            array('FR-13B', 1),
            array('ELE-J3.1', 1),
            array('ELE-E2.2', 1),
            array('VIE AREA', 1),
            array('B7', 1),
            array('WHSE GROUN', 1),
            array('L2B1.5', 1),
            array('L8B4.21', 1),
            array('ANNEX P5', 1),
            array('CLINIC', 1),
            array('LAB-C1.2', 1),
            array('ELE-G3.3', 1),
            array('ELE-C4.1', 1),
            array('WR-A3', 1),
            array('L2B6.17', 1),
            array('Q5', 1),
            array('ELE-A2.1', 1),
            array('SR-A8.1', 1),
            array('L4A', 1),
            array('L5B', 1),
            array('ELE-H3.6', 1),
            array('L6', 1),
            array('ELE-B1.2', 1),
            array('F3A', 1),
            array('ELE-I2.1', 1),
            array('ELE-J3.7', 1),
            array('SR-D3.2', 1),
            array('LAB-B8', 1),
            array('SRI1.3', 1),
            array('L2B3.13', 1),
            array('OLD CNTN', 1),
            array('ELE-J3.2', 1),
            array('ELE-G4.8', 1),
            array('LAB-A4.1', 1),
            array('ELE-J1.2', 1),
            array('C1', 1),
            array('LAB-C7', 1),
            array('LAB-D4.2', 1),
            array('LAB-D4.5', 1),
            array('O4', 1),
            array('F1B', 1),
            array('L8B4.17', 1),
            array('SR-I1.1', 1),
            array('L8B4.11', 1),
            array('SR-F3.1', 1),
            array('LAB-C3.3', 1),
            array('L2B4.31', 1),
            array('L2B5.8', 1),
            array('ELE-G4.6', 1),
            array('LAB-E2.2', 1),
            array('LAB-D5.4', 1),
            array('K3', 1),
            array('WHSE AREA', 1),
            array('SR-B4.1', 1),
            array('ELE-C4.4', 1),
            array('GROUND', 1),
            array('MINI SHLV3', 1),
            array('L2B3.23', 1),
            array('CD', 1),
            array('R2', 1),
            array('SR-B6.2', 1),
            array('P5', 1),
            array('ELE-J3.4', 1),
            array('K1', 1),
            array('L2B5.6', 1),
            array('F4', 1),
            array('SR-GROUND', 1),
            array('ELE-E1.3', 1),
            array('ELE-A3.1', 1),
            array('L2B5.19', 1),
            array('TE', 1),
            array('G8', 1),
            array('L2B1.13', 1),
            array('K6', 1),
            array('R4', 1),
            array('LAB-C6.5', 1),
            array('ELE-G3.5', 1),
            array('ELE-A2.4', 1),
            array('SR-E2.3', 1),
            array('ELE-K1.6', 1),
            array('Ele-L3.5', 1),
            array('L2B6.13', 1),
            array('L2B6.34', 1),
            array('SR-A4.1', 1),
            array('LAB-C8.3', 1),
            array('LAB-D4.4', 1),
            array('L2B1.6', 1),
            array('WAREHOUSE', 1),
            array('SRL', 1),
            array('ELE-B4.3', 1),
            array('SR-A6.2', 1),
            array('SR-C2.1', 1),
            array('LAB-C2.4', 1),
            array('ELE-H1.4', 1),
            array('L2B3.2', 1),
            array('ELE-D3.2', 1),
            array('CD Plant', 1),
            array('ELE-K1.8', 1),
            array('D8B', 1),
            array('L2B6.4', 1),
            array('SRA7.3', 1),
            array('ELE-I4.1', 1),
            array('L2B5.24', 1),
            array('ENG', 1),
            array('OLD CTN', 1),
            array('LAB-A4', 1),
            array('LAB-A2.2', 1),
            array('LAB-A1.2', 1),
            array('ELE-K1.7', 1),
            array('L2B1.2', 1),
            array('M3', 1),
            array('SR-D2.1', 1),
            array('LAB-C2.2', 1),
            array('LAB-D2.5', 1),
            array('L8B4.18', 1),
            array('SR-I5.5', 1),
            array('LAB-D3.2', 1),
            array('T3', 1),
            array('L2B1.9', 1),
            array('MINI SHLV2', 1),
            array('LAB-B9', 1),
            array('ELE-H2.6', 1),
            array('ELE-I4.2', 1),
            array('ELE-A3.4', 1),
            array('SR-B7.1', 1),
            array('LAB-B2.3', 1),
            array('E2', 1),
            array('L2B2.7', 1),
            array('T6', 1),
            array('ELE-C3', 1),
            array('SR-D1', 1),
            array('L2B4.33', 1),
            array('OUTSIDE', 1),
            array('ELE-D3.3', 1),
            array('R3', 1),
            array('SR-A7.2', 1),
            array('L2B1.23', 1),
            array('ANNEX J', 1),
            array('CAB-C1', 1),
            array('LAB-D5.5', 1),
            array('L2B2.14', 1),
            array('L2B6.24', 1),
            array('L1B', 1),
            array('SR-H1.5', 1),
            array('R7', 1),
            array('L2B3.8', 1),
            array('L8B Area', 1),
            array('N5', 1),
            array('E4', 1),
            array('LAB-D5.1', 1),
            array('LAB-E8.1', 1),
            array('ELE-H1.3', 1),
            array('SM', 1),
            array('SR-B5.5', 1),
            array('M2', 1),
            array('L2B6.11', 1),
            array('A8', 1),
            array('LAB-A6.1', 1),
            array('D6B', 1),
            array('ELE-G2.4', 1),
            array('F', 1),
            array('D7', 1),
            array('SRF4.5', 1),
            array('SRI3.5', 1),
            array('ELE-J4.2', 1),
            array('LAB-C7.4', 1),
            array('Floor', 1),
            array('LAB-D2.4', 1),
            array('L6A', 1),
            array('F6B', 1),
            array('SM1', 1),
            array('LAB-E1.1', 1),
            array('L2B6.3', 1),
            array('WR-B1', 1),
            array('LAB-C4.3', 1),
            array('L2B1.8', 1),
            array('D5B', 1),
            array('L2B6.18', 1),
            array('ELE-B1.7', 1),
            array('SR-I2.4', 1),
            array('B2', 1),
            array('L2B3.27', 1),
            array('WR-B2', 1),
            array('CYLINDER', 1),
            array('LAB-A8', 1),
            array('ELE-F2.2', 1),
            array('SR-D2.2', 1),
            array('L8B4.13', 1),
            array('SR A4', 1),
            array('ELE-C4.5', 1),
            array('F7B', 1),
            array('WHSE MH', 1),
            array('L2B2.11', 1),
            array('L2B4.27', 1),
            array('L2B3.21', 1),
            array('SRH6.4', 1),
            array('Q3A', 1),
            array('ELE-K4.3', 1),
            array('LAB-B4', 1),
            array('B4', 1),
            array('L2B1.1', 1),
            array('ELE-C1.2', 1),
            array('SR-I4', 1),
            array('ELE-J4.3', 1),
            array('SR-A5.1', 1),
            array('LAB-B6.3', 1),
            array('L2B3.17', 1),
            array('D2', 1),
            array('L2B6.36', 1),
            array('ELE-A4.8', 1),
            array('LAB-D2.2', 1),
            array('L2B2.18', 1),
            array('FR-11C', 1),
            array('LAB-D1.2', 1),
            array('LAB-D8.5', 1),
            array('E3', 1),
            array('SR B1', 1),
            array('LAB-E4.3', 1),
            array('LAB-B6.1', 1),
            array('LAB-B6', 1),
            array('ELE-G1.2', 1),
            array('ELE-K1.2', 1),
            array('LAB-D8.2', 1),
            array('LAB-E8.5', 1),
            array('L2B4.28', 1),
            array('ELE-I4.4', 1),
            array('E7', 1),
            array('ELE-A3.2', 1),
            array('SR A3', 1),
            array('D4', 1),
            array('ELE-A3.7', 1),
            array('K2', 1),
            array('L2B5.18', 1),
            array('RMB10', 1),
            array('L2B4.25', 1),
            array('L2B5.20', 1),
            array('LA3', 1),
            array('LAB-B5.3', 1),
            array('SR-C1', 1),
            array('F4A', 1),
            array('LAB-C6.1', 1),
            array('LAB-E2.1', 1),
            array('L', 1),
            array('SR-B3.1', 1),
            array('L2B1.24', 1),
            array('ELE-G4.2', 1),
            array('K4', 1),
            array('L2B4.26', 1),
            array('K9', 1),
            array('LAB-E4.5', 1),
            array('ELE-D4.1', 1),
            array('ELE-A2.3', 1),
            array('L3', 1),
            array('D7B', 1),
            array('LAB-E2.5', 1),
            array('LAB-A5.2', 1),
            array('L2B4.34', 1),
            array('ELE-I2.3', 1),
            array('Q1', 1),
            array('FR-26', 1),
            array('CAB-A1', 1),
            array('L8B4.14', 1),
            array('L2B6.20', 1),
            array('ELE-B4.5', 1),
            array('L7', 1),
            array('FR-19', 1),
            array('SM GROUND', 1),
            array('D3B', 1),
            array('F3B', 1),
            array('L2B6.19', 1),
            array('ELE-K3.2', 1),
            array('L2B2.21', 1),
            array('L2B5.13', 1),
            array('SR-H3.4', 1),
            array('LB1', 1),
            array('', 1),
            array('LAB-D5.2', 1),
            array('SR-I3.2', 1),
            array('ELE-B4.2', 1),
            array('L2B4.4', 1),
            array('LAB-C3.4', 1),
            array('LAB-B3.2', 1),
            array('L2B1.17', 1),
            array('L2B3.18', 1),
            array('ER', 1),
            array('ELE-G4.3', 1),
            array('ELE-C3.4', 1),
            array('L2B6.35', 1),
            array('M4', 1),
            array('ELE-K3.3', 1),
            array('T2', 1),
            array('ANNEX', 1),
            array('L2B5.26', 1),
            array('C3', 1),
            array('SR-D2.3', 1),
            array('ELE-B3.6', 1),
            array('LAB-E6.1', 1),
            array('F5', 1),
            array('T4', 1),
            array('L2B2.13', 1),
            array('FR-12', 1),
            array('ELE-I2.2', 1),
            array('L2B6.32', 1),
            array('T9', 1),
            array('ELE-D4.4', 1),
            array('Q7B', 1),
            array('LAB-B1.2', 1),
            array('L2B5.1', 1),
            array('C7', 1),
            array('FR-25', 1),
            array('C6', 1),
            array('L2B4.8', 1),
            array('CIVIL AREA', 1),
            array('ELE-I1.3', 1),
            array('ELE-A2.5', 1),
            array('ELE-C2.4', 1),
            array('H1/H2/H3/H', 1),
            array('SR A1', 1),
            array('C8', 1),
            array('ELE-I3.1', 1),
            array('LAB-B4.3', 1),
            array('LAB-D7.1', 1),
            array('L2B4.7', 1),
            array('SRF2.4', 1),
            array('ELE-J4.1', 1),
            array('K7', 1),
            array('SR-D3.3', 1),
            array('WR-B3', 1),
            array('ELE-K4.1', 1),
            array('MINI SHLV7', 1),
            array('LAB-D6.4', 1),
            array('MINI SHLV', 1),
            array('ELE-H4.5', 1),
            array('LAB-C Area', 1),
            array('ELE-J2.4', 1),
            array('SR-B2.2', 1),
            array('ANNEX A1', 1),
            array('LAB-D7.4', 1),
            array('Q', 1),
            array('F2/F3', 1),
            array('Fabricatio', 1),
            array('FR-11B', 1),
            array('ELE-H4.2', 1),
            array('L2B3.6', 1),
            array('ELE-C1.3', 1),
            array('ARCOSB2', 1),
            array('H5', 1),
            array('LAB-A4.3', 1),
            array('D2A', 1),
            array('G', 1),
            array('L2B1.21', 1),
            array('L2B6.30', 1),
            array('TEMP', 1),
            array('LAB-C3.5', 1),
            array('L8B4.15', 1),
            array('ELE-D1.1', 1),
            array('ELE-K4.4', 1),
            array('L2B4.22', 1),
            array('L2B3.14', 1),
            array('WHSE CD Ar', 1),
            array('ELE-G2.3', 1),
            array('ELE-J4.4', 1),
            array('LAB-A3.3', 1),
            array('LAB-D2.1', 1),
            array('ELE-I3.4', 1),
            array('SR-E1.3', 1),
            array('SR-B7.2', 1),
            array('FR-24', 1),
            array('HR', 1),
            array('SR-I4.4', 1),
            array('LA5', 1),
            array('ELE-J3.6', 1),
            array('SR-H1.4', 1),
            array('L2B3.9', 1),
            array('SRF2.1', 1),
            array('ELE-D3.1', 1),
            array('LAB-C7.2', 1),
            array('N1', 1),
            array('MINI SHLV6', 1),
            array('T7', 1),
            array('FR-13A', 1),
            array('E5', 1),
            array('L2B6.5', 1),
            array('ANNEX N', 1),
            array('ELE-G2.5', 1),
            array('LABOFC', 1),
            array('LAB-A1.1', 1),
            array('LAB-E7.1', 1),
            array('MINI SHLV8', 1),
            array('SR-I5.3', 1),
            array('ELE-I4.3', 1),
            array('G2/G3', 1),
            array('LAB-A5.1', 1),
            array('L2B3.24', 1),
            array('N6', 1),
            array('LAB-D1.4', 1),
            array('L2B2.9', 1),
            array('L2B4.36', 1),
            array('SR-B4.2', 1),
            array('LAB-C4.4', 1),
            array('LAB-D7.5', 1),
            array('ANNEX GROU', 1),
            array('L2B1.11', 1),
            array('L2B4.24', 1),
            array('L8A', 1),
            array('LAB OFFICE', 1),
            array('L8B4.16', 1),
            array('SR-E2.1', 1),
            array('LAB-D3.1', 1),
            array('L2B1.18', 1),
            array('F5A', 1),
            array('FR-13', 1),
            array('ELE-D3.4', 1),
            array('ELE-A4.7', 1),
            array('LAB-E4.4', 1),
            array('L3A', 1),
            array('CONTAINER', 1),
            array('L2', 1),
            array('B5', 1),
            array('L2B3.30', 1),
            array('L2A', 1),
            array('SR-A5.2', 1),
            array('LAB-C6.3', 1),
            array('Lab Area', 1),
            array('RMB12', 1),
            array('L2B2.17', 1),
            array('L2B5.22', 1),
            array('L2B5.25', 1),
            array('SR-A4.2', 1),
            array('LAB-D1.1', 1),
            array('L4B', 1),
            array('INSIDE WAR', 1),
            array('ELE-C1.1', 1),
            array('CIROSB2', 1),
            array('LAB-B7.3', 1),
            array('A5', 1),
            array('L4', 1),
            array('ELE-A3.6', 1),
            array('LAB-E8.2', 1),
            array('SR-I3.1', 1),
            array('L2B2.5', 1),
            array('D5', 1),
            array('F1/F2/F3/F', 1),
            array('I3', 1),
            array('L2B4.6', 1),
            array('SR-I2.3', 1),
            array('ELE-I3.7', 1),
            array('ELE-H4.4', 1),
            array('L2B3.28', 1),
            array('ELE-E3.4', 1),
            array('ELE-B2.4', 1),
            array('LAB-C7.3', 1),
            array('L2B6.22', 1),
            array('ELE-A1.2', 1),
            array('LAB-D3.3', 1),
            array('I1', 1),
            array('L2B3.11', 1),
            array('L2B5.17', 1),
            array('F8A', 1),
            array('ELE-H4.1', 1),
            array('L2B5.11', 1),
            array('ANNEX H', 1),
            array('LAB-C4.5', 1),
            array('CAB-A2', 1),
            array('LAB-D4.3', 1),
            array('LAB-C1.1', 1),
            array('L2B2.19', 1),
            array('L2B6.29', 1),
            array('LAB-C3.2', 1),
            array('L2B3.25', 1),
            array('L2B1.16', 1),
            array('ELE-D4.2', 1),
            array('Q3', 1),
            array('L2B2.1', 1),
            array('SR-FGH6', 1),
            array('SR C6', 1),
            array('FR-17', 1),
            array('F1A', 1),
            array('LA8', 1),
            array('WHSE OFFIC', 1),
            array('L2B4.3', 1),
            array('D5A', 1),
            array('D1A', 1),
            array('LAB-A7.3', 1),
            array('ELE-H1.2', 1),
            array('ELE-D1.2', 1),
            array('L2B2.10', 1),
            array('L2B3.20', 1),
            array('L2B3.26', 1),
            array('ANNEX K', 1),
            array('ELE-K3.4', 1),
            array('ELE-A4.4', 1),
            array('OFC SUP', 1),
            array('C', 1),
            array('ELE-J1.1', 1),
            array('F3/SR', 1),
            array('ELE-C4.6', 1),
            array('B1', 1),
            array('ANNEX E', 1),
            array('ELE-A4.5', 1),
            array('LAB-B6.2', 1),
            array('LAB-A3.1', 1),
            array('LAB-D2.3', 1),
            array('L2B1.15', 1),
            array('ELE-J2.1', 1),
            array('ELE-C2.5', 1),
            array('L2B3.7', 1),
            array('L2B4.29', 1),
            array('SR-I2.1', 1),
            array('SR 5', 1),
            array('ELE-G2.6', 1),
            array('ELE-C2.3', 1),
            array('Ele.K1.3', 1),
            array('A1', 1),
            array('LAB-D7.2', 1),
            array('SRI1.5', 1),
            array('L2B1.3', 1),
            array('ELE-K3.1', 1),
            array('ELE-A4.1', 1),
            array('LAB-C8.4', 1),
            array('ELE-G1.3', 1),
            array('N2', 1),
            array('L2B6.10', 1),
            array('P1', 1),
            array('ELE-J2.5', 1),
            array('ANNEX G', 1),
            array('ELE-A2.6', 1),
            array('ELE-A1.3', 1),
            array('SR-E3.1', 1),
            array('L2B5.16', 1),
            array('SRF1.4', 1),
            array('ELE-L2.2', 1),
            array('ELE-G3.8', 1),
            array('LAB-D8.3', 1),
            array('L2B1.14', 1),
            array('H1', 1),
            array('ELE-C2.1', 1),
            array('R5', 1),
            array('D8A', 1),
            array('P6', 1),
            array('N4', 1),
            array('LAB-E8.3', 1),
            array('L2B3.16', 1),
            array('SR-I2.2', 1),
            array('ELE-D4.3', 1),
            array('SR-B2.1', 1),
            array('SR-I1.2', 1),
            array('G1', 1),
            array('L2B4.32', 1),
            array('WR-B4', 1),
            array('SR-H2.4', 1),
            array('LAB-C5.2', 1),
            array('LAB-C5.5', 1),
            array('G3', 1),
            array('LAB-B2.2', 1),
            array('ELE-J2.3', 1),
            array('staffhouse', 1),
            array('LAB-E6.4', 1),
            array('LAB-D5.3', 1),
            array('L2B3.4', 1),
            array('ELE-J1.4', 1),
            array('D4A', 1),
            array('SR C7', 1),
            array('ELE-A3.5', 1),
            array('H2/H3/H4', 1),
            array('RMB1', 1),
            array('G6', 1),
            array('ELE-A1.6', 1),
            array('ELE-A2.2', 1),
            array('F1/F2', 1),
            array('LAB-B7', 1),
            array('MAGAZINE H', 1),
            array('ELE-G4.4', 1),
            array('C4', 1),
            array('ELE-I1.6', 1),
            array('L2B4.35', 1),
            array('TANK 2G', 1),
            array('L8B4.12', 1),
            array('K5', 1),
            array('L2B5.7', 1),
            array('ELE-G3.4', 1),
            array('ELE-E4.2', 1),
            array('OS', 1),
            array('LAB-C4.2', 1),
            array('O1', 1),
            array('ELE-E4.3', 1),
            array('ELE-B3.1', 1),
            array('Q3B', 1),
            array('N3', 1),
            array('L2B4.30', 1),
            array('L2B5.14', 1),
            array('LA2', 1),
            array('L2B6.12', 1),
            array('LAB C5', 1),
            array('ELE-D2.4', 1),
            array('CH/TE PLNT', 1),
            array('LAB-E4.2', 1),
            array('SR-I2.5', 1),
            array('LAB-C5.4', 1),
            array('L2B2.8', 1),
            array('I2', 1),
            array('ELE-F2.4', 1),
            array('LAB-C8.5', 1),
            array('LAB-E5.4', 1),
            array('SR-C3', 1),
            array('Civil', 1),
            array('LAB-B3.1', 1),
            array('L2B5.5', 1),
            array('SR-A1-2-3', 1),
            array('CD - Whse', 1),
            array('WHSE - MH', 1),
            array('T8', 1),
            array('ELE-H2.4', 1),
            array('ELE-B2.1', 1),
            array('M5', 1),
            array('ELE-J3.5', 1),
            array('L2B1.12', 1),
            array('L8B4.10', 1),
            array('I4', 1),
            array('L2B2.4', 1),
            array('T5', 1),
            array('ELE-A1.1', 1),
            array('F7A', 1),
            array('WR', 1),
            array('F1', 1),
            array('ELE-I2.7', 1),
            array('L2B6.9', 1),
            array('E9', 1),
            array('ELE-I1.1', 1),
            array('P3', 1),
            array('Floor B', 1),
            array('ELE-H4.3', 1),
            array('ELE-B1.4', 1),
            array('B', 1),
            array('LAB-D6.2', 1),
            array('L2B3.1', 1),
            array('ELE-E3.3', 1),
            array('FR-14A', 1),
            array('ELE-A2.7', 1),
            array('CAB-C2', 1),
            array('BACKYARD', 1),
            array('LAB-C5.1', 1),
            array('D1', 1),
            array('Q2', 1),
            array('SR-H2.1', 1),
            array('J1', 1),
            array('L5A', 1),
            array('ELE-H3.5', 1),
            array('LAB-C6', 1),
            array('A6', 1),
            array('CD Area', 1),
            array('SRF5', 1),
            array('L8B4.20', 1),
            array('ELE-G2.7', 1),
            array('L2B3.15', 1),
            array('L27', 1),
            array('ELE-A1.5', 1),
            array('SR-H1.3', 1),
            array('ELE-J1.3', 1),
            array('J6', 1),
            array('L2B3.12', 1),
            array('Wire Room', 1),
            array('Fab. Area', 1),
            array('LAB-A7', 1),
            array('L2B5.2', 1),
            array('L7A', 1),
            array('ELE-B2.5', 1),
            array('SR', 1),
            array('ELE-G2.2', 1),
            array('SRG5.1', 1),
            array('ELE-I3.6', 1),
            array('ELE-B2.3', 1),
            array('LAB-C8.1', 1),
            array('B9', 1),
            array('ELE-K2.1', 1),
            array('LAB-C1.3', 1),
            array('L2B5.15', 1),
            array('SR-H2.2', 1),
            array('FR-10', 1),
            array('L2B4.2', 1),
            array('L2B3.22', 1),
            array('ELE-E3.1', 1),
            array('WR-A4', 1),
            array('D7A', 1),
            array('ELE-B3.4', 1),
            array('WHSE', 1),
            array('ELE-G1.4', 1),
            array('SRH1.1', 1),
            array('ADM', 1),
            array('LAB-E1.2', 1),
            array('FR-14', 1),
            array('ANNEX I', 1),
            array('ELE-G4.5', 1),
            array('D9', 1),
            array('SR-B2', 1)
        );

        foreach($locations as $location) {
            $loc = new \App\Location();
            $loc->Name = $location[0];
            $loc->Status = $location[1];
            $loc->save();
        }

        $loc = new \App\Location();
        $loc->Name = 'Unknown';
        $loc->Status = 1;
        $loc->save();
        $loc->ID = 0;
        $loc->save();

        $supplierTypes = array(
            'AP P',
            'AP $',
            'AP LEWER',
            'INTERCO',
            'FREIGHT',
            'OTHERS',
            'REG EMP',
            'RES EMP'
        );

        foreach($supplierTypes as $supplierType) {
            $s = new App\SupplierType();
            $s->Description = $supplierType;
            $s->save();
        }

        $currencies = array(
            array("SGD","SINGAPORE DOLLAR",1.34960,34.16700),
            array("AUD","AUSTRALIAN DOLLAR",.75220,40.70870),
            array("RMB","CHINESE YUAN",.20000,6.13700),
            array("PHP","PHILIPPINE PESO",.01917,1.00000),
            array("USD","US DOLLAR",1.00000,52.16000),
            array("EUR","EURO",1.01300,52.26000),
            array("GBP","BRITISH POUND",1.31780,65.00400)
        );

        foreach($currencies as $currency) {
            $c = new \App\Currency();
            $c->Code = $currency[0];
            $c->Name = $currency[1];
            $c->USD = $currency[2];
            $c->PHP = $currency[3];
            $c->save();
        }

        $user = auth()->user();
        $user->Department = 24;
        $user->save();

        auth()->logout();
    }
}